export type MuscleGroup = 'Back' | 'Legs' | 'Chest' | 'Arms' | 'Shoulders' | 'Core';

export const MUSCLE_GROUPS: MuscleGroup[] = ['Back', 'Legs', 'Chest', 'Arms', 'Shoulders', 'Core'];

/**
 * Mapping of Hevy exercise names to muscle groups (including compound exercises
 * that target multiple muscle groups).
 * Includes standard Hevy exercises scraped from https://www.hevyapp.com/exercises/
 * and all exercises from user workout data.
 */
export const EXERCISE_MUSCLE_MAPPING: Record<string, MuscleGroup[]> = {
  'Arnold Press (Dumbbell)': ['Shoulders', 'Arms'],
  'Around The World': ['Chest', 'Shoulders'],
  'Back Extension (Weighted Hyperextension)': ['Back', 'Legs'],
  'Behind the Back Bicep Wrist Curl (Barbell)': ['Arms'],
  'Bench Press (Barbell)': ['Chest', 'Arms', 'Shoulders'],
  'Bench Press (Dumbbell)': ['Chest', 'Arms', 'Shoulders'],
  'Bench Press (Smith Machine)': ['Chest', 'Arms', 'Shoulders'],
  'Bench Press - Close Grip (Barbell)': ['Arms', 'Chest', 'Shoulders'],
  'Bench Press - Wide Grip (Barbell)': ['Chest', 'Shoulders'],
  'Bent over fly': ['Shoulders', 'Back'],
  'Bent Over Row (Barbell)': ['Back', 'Arms', 'Core'],
  'Bicep Curl (Barbell)': ['Arms'],
  'Bicep Curl (Cable)': ['Arms'],
  'Bicep Curl (Dumbbell)': ['Arms'],
  'Bulgarian Split Squat': ['Legs', 'Core'],
  'Cable Crunch': ['Core'],
  'Calf Press (Machine)': ['Legs'],
  'Chest Dip': ['Chest', 'Arms', 'Shoulders'],
  'Chest Dip (Assisted)': ['Chest', 'Arms', 'Shoulders'],
  'Chest Dip (Weighted)': ['Chest', 'Arms', 'Shoulders'],
  'Chest Fly (Machine)': ['Chest'],
  'Chest Press (Machine)': ['Chest', 'Arms', 'Shoulders'],
  'Chest Supported Incline Row (Dumbbell)': ['Back', 'Arms'],
  'Chest-Supported Incline Row (dumbbell)': ['Back', 'Arms'],
  'Chin Up': ['Back', 'Arms'],
  'Clean Pull': ['Back', 'Legs'],
  'Clean and Jerk': ['Legs', 'Back', 'Shoulders', 'Arms'],
  'Climbing': ['Back', 'Arms', 'Core'],
  'Concentration Curl': ['Arms'],
  'Dead Hang': ['Back', 'Arms'],
  'Deadlift (Band)': ['Back', 'Legs', 'Core'],
  'Deadlift (Barbell)': ['Back', 'Legs', 'Core'],
  'Deadlift (Dumbbell)': ['Back', 'Legs', 'Core'],
  'Deadlift (Trap bar)': ['Legs', 'Back', 'Core'],
  'Decline Bench Press (Dumbbell)': ['Chest', 'Arms'],
  'Decline Bench Press (Machine)': ['Chest', 'Arms'],
  'Decline Crunch': ['Core'],
  'Decline Crunch (Weighted)': ['Core'],
  'Decline Push Up': ['Chest', 'Shoulders', 'Arms', 'Core'],
  'Diamond Push Up': ['Arms', 'Chest'],
  'Dumbbell Row': ['Back', 'Arms'],
  'Dumbbell Skullcrusher': ['Arms'],
  'Face Pull': ['Shoulders', 'Back'],
  'Farmer\'s Walk': ['Arms', 'Back', 'Core'],
  'Fire Hydrants': ['Legs'],
  'Floor Press (Barbell)': ['Chest', 'Arms', 'Shoulders'],
  'Flutter Kicks': ['Core'],
  'Frog Jumps': ['Legs'],
  'Front Lever Raise': ['Core', 'Back'],
  'Front Squat': ['Legs', 'Core', 'Back'],
  'Glute Bridge': ['Legs'],
  'Glute Ham Raise': ['Legs', 'Back'],
  'Glute Kickback (Machine)': ['Legs'],
  'Glute Kickback on Floor': ['Legs'],
  'Goblet Squat': ['Legs', 'Core'],
  'Good Morning (Barbell)': ['Legs', 'Back', 'Core'],
  'Hack Squat': ['Legs'],
  'Hack Squat (Machine)': ['Legs'],
  'Hammer Curl (Band)': ['Arms'],
  'Hammer Curl (Cable)': ['Arms'],
  'Hammer Curl (Dumbbell)': ['Arms'],
  'Handstand Push Up': ['Shoulders', 'Arms', 'Core'],
  'Hang Snatch': ['Legs', 'Back', 'Shoulders'],
  'Heel Taps': ['Core'],
  'Hip Abduction (Machine)': ['Legs'],
  'Hip Adduction (Machine)': ['Legs'],
  'Hip Thrust': ['Legs'],
  'Hip Thrust (Barbell)': ['Legs'],
  'Hip Thrust (Machine)': ['Legs'],
  'Hollow Rock Hold': ['Core'],
  'Incline Bench Press (Barbell)': ['Chest', 'Shoulders', 'Arms'],
  'Incline Bench Press (Dumbbell)': ['Chest', 'Shoulders', 'Arms'],
  'Incline Bench Press (Smith Machine)': ['Chest', 'Shoulders', 'Arms'],
  'Incline Chest Fly (Dumbbell)': ['Chest'],
  'Incline Chest Press (Machine)': ['Chest', 'Shoulders', 'Arms'],
  'Incline Push Ups': ['Chest', 'Arms'],
  'Iso-Lateral Low Row': ['Back', 'Arms'],
  'Jackknife Sit Up': ['Core'],
  'Jump Squat': ['Legs'],
  'Kettlebell Goblet Squat': ['Legs', 'Core'],
  'Kettlebell Turkish Get Up': ['Core', 'Shoulders', 'Legs', 'Arms'],
  'Kipping Pull Up': ['Back', 'Arms', 'Core'],
  'Knee Raise Parallel Bars': ['Core'],
  'Lat Pulldown (Cable)': ['Back', 'Arms'],
  'Lat Pulldown (Machine)': ['Back', 'Arms'],
  'Lat Pulldown (band)': ['Back', 'Arms'],
  'Lat Pulldown - Close Grip (Cable)': ['Back', 'Arms'],
  'Lateral Leg Raises': ['Legs'],
  'Lateral Raise (Cable)': ['Shoulders'],
  'Lateral Raise (Dumbbell)': ['Shoulders'],
  'Lateral Raise (Machine)': ['Shoulders'],
  'Lateral Squat': ['Legs'],
  'Leg Extension (Machine)': ['Legs'],
  'Leg Press (Machine)': ['Legs'],
  'Leg Press Horizontal (Machine)': ['Legs'],
  'Leg Raise Parallel Bars': ['Core'],
  'Lunge (Barbell)': ['Legs', 'Core'],
  'Lunge (Dumbbell)': ['Legs', 'Core'],
  'Lying Knee Raise': ['Core'],
  'Lying Leg Curl (Machine)': ['Legs'],
  'Meadows Row': ['Back', 'Arms'],
  'Muscle Up': ['Back', 'Arms', 'Chest', 'Core'],
  'Oblique Crunch': ['Core'],
  'One-Arm Push-Up': ['Chest', 'Arms', 'Core'],
  'One-Arm Tricep Extension (Dumbbell)': ['Arms'],
  'Overhead Press (Smith Machine)': ['Shoulders', 'Arms'],
  'Overhead Squat': ['Legs', 'Shoulders', 'Core', 'Back'],
  'Overhead Triceps Extension (Cable)': ['Arms'],
  'Pendlay Row': ['Back', 'Arms', 'Core'],
  'Pendulum Squat (Machine)': ['Legs'],
  'Pinwheel Curl (Dumbbell)': ['Arms'],
  'Plank': ['Core'],
  'Plate Curls': ['Arms'],
  'Plate Front Raise': ['Shoulders'],
  'Plate Press': ['Chest', 'Arms'],
  'Preacher Curl (Barbell)': ['Arms'],
  'Preacher Curl (Dumbbell)': ['Arms'],
  'Preacher Curl (Machine)': ['Arms'],
  'Pull Up': ['Back', 'Arms', 'Core'],
  'Pull Up (Assisted)': ['Back', 'Arms'],
  'Pullover (Dumbbell)': ['Chest', 'Back'],
  'Push Press': ['Shoulders', 'Legs', 'Arms'],
  'Push Up': ['Chest', 'Arms', 'Shoulders', 'Core'],
  'Push Up (Weighted)': ['Chest', 'Arms', 'Shoulders', 'Core'],
  'Rack Pull': ['Back', 'Legs'],
  'Rear Delt Reverse Fly (Machine)': ['Shoulders', 'Back'],
  'Renegade Row': ['Back', 'Core', 'Arms'],
  'Reverse Curl': ['Arms'],
  'Reverse Lunge': ['Legs', 'Core'],
  'Reverse Plank': ['Core'],
  'Ring Dips': ['Chest', 'Arms', 'Shoulders', 'Core'],
  'Romanian Deadlift (Barbell)': ['Legs', 'Back'],
  'Romanian Deadlift (Dumbbell)': ['Legs', 'Back'],
  'Russian Twist (Bodyweight)': ['Core'],
  'Russian Twist (weighted)': ['Core'],
  'Scapular Pull-ups': ['Back'],
  'Seated Cable Row - Bar Grip': ['Back', 'Arms'],
  'Seated Cable Row - Bar Wide Grip': ['Back', 'Arms'],
  'Seated Cable Row - V Grip (Cable)': ['Back', 'Arms'],
  'Seated Calf Raise': ['Legs'],
  'Seated Calf Raises': ['Legs'],
  'Seated Leg Curl (Machine)': ['Legs'],
  'Seated Overhead Press (Barbell)': ['Shoulders', 'Arms'],
  'Seated Shoulder Press (Machine)': ['Shoulders', 'Arms'],
  'Shoulder Press (Dumbbell)': ['Shoulders', 'Arms'],
  'Shoulder Press (Machine Plates)': ['Shoulders', 'Arms'],
  'Shrug (Barbell)': ['Back', 'Shoulders'],
  'Shrug (Dumbbell)': ['Back', 'Shoulders'],
  'Side Bend (Dumbbell)': ['Core'],
  'Single Arm Cable Row': ['Back', 'Arms'],
  'Single Arm Curl (Cable)': ['Arms'],
  'Single Arm Lat Pulldown': ['Back', 'Arms'],
  'Single Arm Lateral Raise (Cable)': ['Shoulders'],
  'Single Leg Glute Bridge': ['Legs'],
  'Single Leg Hip Thrust': ['Legs'],
  'Single Leg Press (Machine)': ['Legs'],
  'Single Leg Romanian Deadlift (Dumbbell)': ['Legs', 'Back'],
  'Single Leg Standing Calf Raise': ['Legs'],
  'Sissy Squat': ['Legs'],
  'Sit Ups': ['Core'],
  'Skullcrusher (barbell)': ['Arms'],
  'Spider Curl (Dumbbell)': ['Arms'],
  'Spiderman': ['Core'],
  'Split Squat (Dumbbell)': ['Legs', 'Core'],
  'Squat (Barbell)': ['Legs', 'Core', 'Back'],
  'Squat (Bodyweight)': ['Legs', 'Core'],
  'Squat (Machine)': ['Legs', 'Core'],
  'Squat (Smith Machine)': ['Legs', 'Core'],
  'Stair Machine (Steps)': ['Legs'],
  'Standing Calf Raise (Machine)': ['Legs'],
  'Standing Leg Curls': ['Legs'],
  'Standing Military Press (Barbell)': ['Shoulders', 'Arms', 'Core'],
  'Sternum Pull up (Gironda)': ['Back', 'Arms'],
  'Stiff / straight leg deadlift': ['Legs', 'Back'],
  'Sumo Deadlift': ['Legs', 'Back'],
  'Sumo Squat (barbell)': ['Legs', 'Core'],
  'Superman': ['Back', 'Core'],
  'T Bar Row': ['Back', 'Arms'],
  'Thruster (Kettlebell)': ['Legs', 'Shoulders', 'Arms'],
  'Triceps Dip (Weighted)': ['Arms', 'Chest', 'Shoulders'],
  'Triceps Extension (Cable)': ['Arms'],
  'Triceps Extension (Dumbbell)': ['Arms'],
  'Triceps Extension (Suspension)': ['Arms'],
  'Triceps Extension (barbell)': ['Arms'],
  'Triceps Kickback': ['Arms'],
  'Triceps Pushdown': ['Arms'],
  'Triceps Rope Pushdown': ['Arms'],
  'Upright Row (Barbell)': ['Shoulders', 'Arms', 'Back'],
  'V Up': ['Core'],
  'Walking': ['Legs'],
  'Wall Sit': ['Legs'],
  'Zercher Squat': ['Legs', 'Core', 'Back', 'Arms'],
  'Zottman Curl (Dumbbell)': ['Arms'],
  'painting': ['Arms', 'Shoulders'],
};

export const exerciseMuscleMapping = EXERCISE_MUSCLE_MAPPING;

export default EXERCISE_MUSCLE_MAPPING;
